---
title: "README"
output: html_document
---

#### TimeseriesCalibration.Rmd
The TimeseriesCalibration.Rmd tries to reproduce the Fig 3A from in Zani et al. 2020.

Timeseries (site-species) calibration outputs are gather together after being run in Euler.

Fig 3A is presented following the code in ModelAnalysis_3_Models_Performance.R provided by the authors.

#### ComparePredictions
The ComparePredictions.Rmd file compares the predicted autumn senescense read from the ModelAnalysis_1_Predicted_DoYoff_subset.csv file provided by Zani et al. in Zenodo with the predictions resulting from evaluating the models using the optimal parameters read from ModelAnalysis_2_OptimalParameters_subset.csv and data.sub for the 3 timeseries provided.

#### ExampleCalibration.Rmd
The ExampleCalibration.Rmd file tries to reproduce the timeseries (site-species) calibration done by Zani et al. 2020.

The example mostly uses the script ModelAnalyses_2_AutumnPhenology_Optimization_Predictions.R provided by the authors in Zenodo (with some changes needed for running the particular case of 2 timeseries).

The data used in the model calibration includes the drivers provided by the authors (data/DataMeta_3_Drivers_20_11_10.csv), and two more inputs: minimum temperature (data/MinimumTemperature.csv) and photoperiod (data/Photoperiod_daylength.csv) calculated from the data site information. 

From these mentioned data drivers and inputs, the script creates a datalist with the structure needed for the calibration sing the phenor package.

Definitions of the models are used as presented by Zani et al. 2020. However, we have identified possible errors in the original script ModelAnalyses_2_AutumnPhenology_Optimization_Predictions.R that may need to be discussed (see #xxx? in the script)

This calibration example is done for two timeseries (1_Fagus_Sylvatica and 1_Quercus_robur) and the outputs are saved as follows: output/DoYoff_Preds.df_1_Fagus_sylvatica.RData and output/DoYoff_Preds.df_1_Quercus_robur.RData 

The obtained predictions are compared with the subset of predictions provided by the authors in Zenodo (output/ModelAnalysis_1_Predicted_DoYoff_subset.csv) that includes the two timeseries selected for this example.

