---
title: "TimeseriesCalibration"
output: html_document
---

```{r setup, include=FALSE}
# Load libraries
library(data.table)
library(tidyverse)
library(broom)
library(Metrics)
library(lmodel2)
library(ggplot2)
library(phenor)
#detach(package:phenor)
library(ggpubr)
```

#### Aggregate all outputs (timeseries calibration) from Euler 

```{r,include=FALSE,eval=TRUE}
setwd("~/pep_calib_euler_data3")
all.files=as.vector(dir(pattern="DoYoff_Preds_*"))

mylist<- lapply(all.files, function(x) {
  load(file = x)
  get(ls()[ls()!= "filename"])
})
names(mylist) <- all.files #Note, the names here don't have to match the filenames

allpredicts <- do.call("rbind", mylist)
rownames(allpredicts) <- NULL
head(allpredicts)
```

#### Plots calibration results as in Zani et al. from ModelAnalysis_3_Models_Performance.R

```{r,echo=FALSE,eval=TRUE}

## FIGURE 3A
# Observed (Obs_AnomDoYoff) vs.
# Predicted (Pred_AnomDoYoff)
# leaf senescence anomalies, i.e., as deviation from the mean observed leaf-out date at each site
# of the best-performing first-generation (TPM) [Lang et al. (2019)], 
# second-generation (TPDM) [Liu et al. (2019)]
# and CarbLim models (PIAM)

#pred_DoYoff <- data.table::fread("~/data/pep/processed/ModelAnalysis_1_Predicted_DoYoff_subset.csv") # Data from Constantin

# Import data
pred_DoYoff <- allpredicts %>% 
  dplyr::filter(Species != "Betula pubescens")

# Select autumn anomalies from best-performing models
best_pred_DoYoff <- pred_DoYoff %>% 
  dplyr::select(Obs_AnomDoYoff,Preds_AnomDoYoff_TPM,Preds_AnomDoYoff_TPDM,`Preds_AnomDoYoff_PIA+`)

# Format dataset for plotting
types <- c("First-generation (TPM)","Second-generation (TPDM)","CarbLim model (PIA+)")
colnames(best_pred_DoYoff) <- c("observations",types)
best_pred_DoYoff <- best_pred_DoYoff %>% 
  pivot_longer(-observations,names_to="model_type",values_to="predictions")
best_pred_DoYoff$model_type <- factor(best_pred_DoYoff$model_type, levels=types)

# Define palette
paletteBlueRed <- c("blue3","white","red3")

# Plot
fig_3a <- ggplot(best_pred_DoYoff, aes(x=predictions, y=observations)) +
  stat_bin2d(bins=235) +
  labs(x = "Predicted autumn anomaly",
       y = "Observed autumn anomaly") +
  coord_cartesian(xlim=c(-50,50), ylim=c(-50,50))+
  scale_fill_gradientn(colours = paletteBlueRed,
                       limits = c(10,2300),
                       breaks = c(100,1200,2200)) +
  geom_abline(slope=1, intercept=0,
              na.rm = FALSE, show.legend = NA, linetype="dashed") +
  theme(aspect.ratio=1,
        legend.position = "right",
        plot.title=element_text(hjust=.5),
        axis.title.y=element_text(size=14),
        axis.text.y=element_text(size=11),
        axis.title.x=element_text(size=14),
        axis.text.x=element_text(size=11),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = 'white', colour = 'black'),
        plot.margin = unit(c(0, 0, 0, 0), "cm")
  ) + 
  facet_wrap(.~model_type, ncol=3)
fig_3a

```

